#!/usr/bin/env python3
"""
Generate device info header from GitHub API or local markdown file.

Generates a C++ header with project metadata for the about screen.
The generated file is NOT committed to the repo (see .gitignore).

Usage:
    python gen_contributors.py                    # Fetch from GitHub API
    python gen_contributors.py --input <file.md>  # Use local markdown file

Environment:
    GH_TOKEN: GitHub personal access token (optional, enables API fetching)
    REPO_OWNER: Repository owner (default: crosspoint-reader)
    REPO_NAME: Repository name (default: crosspoint-reader)

Output:
    src/generated/Contributors.h - C++ header with contributor data
"""

import sys
import os
import re
import json
import argparse
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from datetime import datetime
import urllib.request
import urllib.error


def fetch_from_github_api(owner: str, repo: str, token: Optional[str]) -> List[Dict]:
    """Fetch all merged PRs from GitHub API."""
    contributors: Dict[str, Dict] = {}
    page = 1
    per_page = 100

    headers = {
        "Accept": "application/vnd.github.v3+json"
    }
    if token:
        headers["Authorization"] = f"token {token}"

    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/pulls?state=closed&per_page={per_page}&page={page}"
        req = urllib.request.Request(url, headers=headers)

        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                data = json.loads(response.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 403:
                print("GitHub API rate limit exceeded. Using fallback mode.", file=sys.stderr)
            else:
                print(f"GitHub API error: {e}", file=sys.stderr)
            break
        except Exception as e:
            print(f"Error fetching from GitHub: {e}", file=sys.stderr)
            break

        if not data:
            break

        for pr in data:
            if not pr.get("merged_at"):
                continue
            user = pr.get("user", {})
            if user.get("type") in ("Organization", "Bot"):
                continue
            login = user.get("login")
            if not login:
                continue

            merged_at = pr.get("merged_at")

            if login not in contributors:
                contributors[login] = {
                    "first_merge": merged_at,
                    "count": 1
                }
            else:
                contributors[login]["count"] += 1
                if merged_at < contributors[login]["first_merge"]:
                    contributors[login]["first_merge"] = merged_at

        if len(data) < per_page:
            break
        page += 1
        print(f"Fetched page {page-1}...", file=sys.stderr)

    return contributors


def parse_markdown_file(filepath: str) -> Dict[str, Dict]:
    """Parse CONTRIBUTORS_SIMPLE.md to extract contributors."""
    contributors: Dict[str, Dict] = {}

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.strip().split("\n")
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("|"):
            continue

        parts = [p.strip() for p in line.split("|")]
        if len(parts) >= 3:
            name = parts[1]
            date = parts[2]
            if name and date and date != "First Merged PR":
                contributors[name] = {
                    "first_merge": date,
                    "count": 0
                }

    return contributors


def generate_header(contributors: Dict[str, Dict], output_path: str):
    """Generate Contributors.h header file."""

    sorted_contributors = sorted(
        contributors.items(),
        key=lambda x: x[1]["first_merge"]
    )

    soup_parts = []
    for name, _ in sorted_contributors:
        soup_parts.append(name)

    soup_string = "".join(soup_parts)

    lines = [
        "// Auto-generated by scripts/gen_contributors.py",
        "// DO NOT COMMIT - This file is in .gitignore",
        "// Generated: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "",
        "#ifndef CONTRIBUTORS_H",
        "#define CONTRIBUTORS_H",
        "",
        "#include <cstdint>",
        "",
        f"// Total contributors: {len(sorted_contributors)}",
        f"constexpr uint16_t CONTRIBUTORS_COUNT = {len(sorted_contributors)};",
        "",
        "// Word soup - all usernames concatenated without separators",
        f"const char CONTRIBUTORS_SOUP[] PROGMEM = \"{soup_string}\";",
        "",
        "// Contributor entry with name and first merge date",
        "struct Contributor {",
        "    const char* name;",
        "    const char* date; // \"YYYY-MM-DD\"",
        "};",
        "",
        "// Contributors sorted by first merged PR date (earliest first)",
        "const Contributor CONTRIBUTORS[CONTRIBUTORS_COUNT] PROGMEM = {",
    ]

    for name, data in sorted_contributors:
        date = data["first_merge"][:10]
        lines.append(f'    {{ "{name}", "{date}" }},')

    lines.extend([
        "};",
        "",
        "#endif // CONTRIBUTORS_H"
    ])

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated: {output_path}")
    print(f"  Contributors: {len(sorted_contributors)}")
    print(f"  Soup length: {len(soup_string)} chars")


def generate_placeholder(output_path: str):
    """Generate an empty placeholder when no data is available."""
    lines = [
        "// Auto-generated by scripts/gen_contributors.py",
        "// DO NOT COMMIT - This file is in .gitignore",
        "// Generated: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "",
        "#ifndef CONTRIBUTORS_H",
        "#define CONTRIBUTORS_H",
        "",
        "#include <cstdint>",
        "",
        "// No contributors data available",
        "constexpr uint16_t CONTRIBUTORS_COUNT = 0;",
        "",
        "const char CONTRIBUTORS_SOUP[] PROGMEM = \"\";",
        "",
        "struct Contributor {",
        "    const char* name;",
        "    const char* date;",
        "};",
        "",
        "const Contributor CONTRIBUTORS[1] PROGMEM = {",
        '    { "", "" }',
        "};",
        "",
        "#endif // CONTRIBUTORS_H"
    ]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated placeholder: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate Contributors.h from GitHub API or markdown")
    parser.add_argument("--input", "-i", help="Input markdown file (optional)")
    parser.add_argument("--output", "-o", default="src/generated/Contributors.h",
                        help="Output header file path")
    parser.add_argument("--owner", default=os.environ.get("REPO_OWNER", "crosspoint-reader"),
                        help="Repository owner")
    parser.add_argument("--repo", default=os.environ.get("REPO_NAME", "crosspoint-reader"),
                        help="Repository name")
    args = parser.parse_args()

    contributors = {}

    if args.input:
        if os.path.exists(args.input):
            print(f"Reading from markdown file: {args.input}")
            contributors = parse_markdown_file(args.input)
        else:
            print(f"Input file not found: {args.input}", file=sys.stderr)
    else:
        token = os.environ.get("GH_TOKEN")
        print(f"Fetching from GitHub: {args.owner}/{args.repo}")
        contributors = fetch_from_github_api(args.owner, args.repo, token)

    if contributors:
        generate_header(contributors, args.output)
    else:
        generate_placeholder(args.output)


if __name__ == "__main__":
    main()
else:
    try:
        Import("env")  # noqa: F821  # type: ignore[name-defined]
    except NameError:
        pass
    sys.argv = [sys.argv[0]]
    main()